In [6]:
import pandas as pd
import csv
import numpy as np
import matplotlib.pyplot as plt
#import pyvista as pv
#from pyvistaqt import BackgroundPlotter
import os
import re
#import rasterio

In [7]:
mesh_df = pd.read_csv('C:\\Users\\Gerrit\\Desktop\\Masterarbeit\\masterarbeit_gerrit-main\\data_processed\\Daten10_processed_40.csv.csv')
mesh_list = []
mesh_df

,Unnamed: 0,Index,X,Y,Z,description,elevation,from,id,rockCodeShort,to,totalLength
0,0,0.0,565809.623,5934327.530,-0.90,Wasser,3.10,0.0,BDHH_6436D1014,W,4.0,49.5
1,1,0.0,565809.623,5934327.530,-1.90,Torf,3.10,4.0,BDHH_6436D1014,H,5.0,49.5
2,2,0.0,565809.623,5934327.530,-2.60,"Feinsand bis Mittelsand (schwach grobsandig, h...",3.10,5.0,BDHH_6436D1014,fS,5.7,49.5
3,3,0.0,565809.623,5934327.530,-4.70,"Grobsand bis Mittelsand (humos, feinkiesig, sc...",3.10,5.7,BDHH_6436D1014,gS,7.8,49.5
4,4,0.0,565809.623,5934327.530,-7.40,"Kies (mittelsandig bis grobsandig, steinig)",3.10,7.8,BDHH_6436D1014,G,10.5,49.5
...,...,...,...,...,...,...,...,...,...,...,...,...
644,3,50.0,565694.669,5934386.507,-1.44,Torf,2.86,3.2,BDHH_6436D98,H,4.3,11.0
645,4,50.0,565694.669,5934386.507,-2.24,Feinstsand,2.86,4.3,BDHH_6436D98,f,5.1,11.0
646,5,50.0,565694.669,5934386.507,-3.14,Feinstsand (steinig),2.86,5.1,BDHH_6436D98,f,6.0,11.0
647,6,50.0,565694.669,5934386.507,-5.14,Ton,2.86,6.0,BDHH_6436D98,T,8.0,11.0
648,7,50.0,565694.669,5934386.507,-8.14,Ton,2.86,8.0,BDHH_6436D98,T,11.0,11.0

In [8]:
#Querschnitt 565756E
BohrlÃ¶cher=['BDHH_6436D1123','BDHH_6436D1059','BDHH_6436D1167','BDHH_6436D1046','BDHH_6436D79','BDHH_6436D1166','BDHH_6436D1061','BDHH_6436D1163','BDHH_6436D911','BDHH_6436D1092','BDHH_6436D1625','BDHH_6436D97']
mesh_df = mesh_df[mesh_df['id'].isin(BohrlÃ¶cher)]
mesh_df

,Unnamed: 0,Index,X,Y,Z,description,elevation,from,id,rockCodeShort,to,totalLength
251,0,12.0,565767.639,5934259.557,5.1,Schwarzdecke (StraÃƒÅ¸enasphalt) bis Steine,5.45,0.00,BDHH_6436D1046,ygs,0.35,25.6
252,1,12.0,565767.639,5934259.557,4.7,"Feinsand bis Grobsand (kiesig, steinig), Bausc...",5.45,0.35,BDHH_6436D1046,fS,0.75,25.6
253,2,12.0,565767.639,5934259.557,3.1,"(Ziegelreste, Beton) (TrÃƒÂ¼mmer)",5.45,0.75,BDHH_6436D1046,yz,2.35,25.6
254,3,12.0,565767.639,5934259.557,2.3,Feinsand,5.45,2.35,BDHH_6436D1046,fS,3.15,25.6
255,4,12.0,565767.639,5934259.557,0.5,"Feinsand bis Mittelsand (schluffig, Holzreste,...",5.45,3.15,BDHH_6436D1046,fS,4.95,25.6
...,...,...,...,...,...,...,...,...,...,...,...,...
636,6,49.0,565745.649,5934357.519,-5.6,"Feinstsand (steinig, gerÃƒÂ¶llfÃƒÂ¼hrend)",3.80,6.30,BDHH_6436D97,f,9.40,18.8
637,7,49.0,565745.649,5934357.519,-7.1,Mudde,3.80,9.40,BDHH_6436D97,F,10.90,18.8
638,8,49.0,565745.649,5934357.519,-8.0,Feinstsand,3.80,10.90,BDHH_6436D97,f,11.80,18.8
639,9,49.0,565745.649,5934357.519,-9.6,"Feinstsand (steinig, gerÃƒÂ¶llfÃƒÂ¼hrend)",3.80,11.80,BDHH_6436D97,f,13.40,18.8
640,10,49.0,565745.649,5934357.519,-15.0,"Ton (schwach sandig, gerÃƒÂ¶llfÃƒÂ¼hrend)",3.80,13.40,BDHH_6436D97,T,18.80,18.8

In [9]:
df = mesh_df.drop(columns=['X','Index', 'description', 'elevation', 'totalLength','from', 'to', 'totalLength' ])

In [10]:
df.rename({'rockCodeShort': 'Facies'}, axis=1, inplace=True)
df

     Unnamed: 0            Y     Z              id Facies
251           0  5934259.557   5.1  BDHH_6436D1046    ygs
252           1  5934259.557   4.7  BDHH_6436D1046     fS
253           2  5934259.557   3.1  BDHH_6436D1046     yz
254           3  5934259.557   2.3  BDHH_6436D1046     fS
255           4  5934259.557   0.5  BDHH_6436D1046     fS
..          ...          ...   ...             ...    ...
636           6  5934357.519  -5.6    BDHH_6436D97      f
637           7  5934357.519  -7.1    BDHH_6436D97      F
638           8  5934357.519  -8.0    BDHH_6436D97      f
639           9  5934357.519  -9.6    BDHH_6436D97      f
640          10  5934357.519 -15.0    BDHH_6436D97      T

[161 rows x 5 columns]

In [11]:
# Suchen und Ersetzen
neuer_name = 'y'
alter_name = 'yy', 'ygs', 'ys', 'yz'

# Ersetzen 
df['Facies'] = df['Facies'].replace(alter_name, neuer_name)

In [12]:
# Suchen und Ersetzen
neuer_name = 'G'
alter_name = 'mG', 'gG'

# Ersetzen
df['Facies'] = df['Facies'].replace(alter_name, neuer_name)

In [13]:
# Suchen und Ersetzen
neuer_name = 'H'
alter_name = 'F'

# Ersetzen 
df['Facies'] = df['Facies'].replace(alter_name, neuer_name)

In [14]:
# Suchen und Ersetzen
neuer_name = 'gS'
alter_name = 'fG'

# Ersetzen 
df['Facies'] = df['Facies'].replace(alter_name, neuer_name)

In [15]:
# Suchen und Ersetzen
neuer_name = 'S'
alter_name = 'default', 'y', 'Kl', 'brk'

# Ersetzen 
df['Facies'] = df['Facies'].replace(alter_name, neuer_name)

In [16]:
# Suchen und Ersetzen
neuer_name = 'fS'
alter_name = 'f'

# Ersetzen 
df['Facies'] = df['Facies'].replace(alter_name, neuer_name)

In [17]:
unique_entries = df['Facies'].unique()

# Ausgabe der einzigartigen EintrÃ¤ge
print(unique_entries)

['S' 'fS' 'H' 'U' 'mS' 'G' 'gS' 'Fkm' 'Mg' 'T']

In [18]:
interval_size = 0.5 #m
big_new_df = pd.DataFrame()
groups = df.groupby(['id'])
for id, subdf in groups:
    subdf = subdf[::-1]
    new_df = pd.DataFrame()
    all_new_ys = []
    all_new_zs = []
    all_new_facies = []
    for i in range(len(subdf)-1):
        a = subdf['Z'].values[i]
        b = subdf['Z'].values[i+1]
        new_z = np.arange(b, a, -interval_size)[::-1]
        new_facies = list(np.repeat(subdf['Facies'].values[i], len(new_z)-1))
        new_facies.append(subdf['Facies'].values[i+1])
        new_y = np.repeat(subdf['Y'].values[i+1], len(new_z))
        for j in range(len(new_z)):
            all_new_zs.append(new_z[j])
            all_new_ys.append(new_y[j])
            all_new_facies.append(new_facies[j])

    new_df['Y'] = np.array(all_new_ys).ravel()[::-1]
    new_df['Z'] =  np.array(all_new_zs).ravel()[::-1]
    new_df['Facies'] =  np.array(all_new_facies).ravel()[::-1]
    big_new_df = pd.concat((big_new_df, new_df))

In [19]:
for facies in big_new_df['Facies'].unique():
    if facies in df['Facies'].unique():
        pass
    else:
        print('----', facies)

In [20]:
df=big_new_df
df

              Y     Z Facies
0   5934259.557   5.1      S
1   5934259.557   4.7     fS
2   5934259.557   4.2      S
3   5934259.557   3.7      S
4   5934259.557   3.2      S
..          ...   ...    ...
34  5934357.519 -12.6      T
35  5934357.519 -13.1      T
36  5934357.519 -13.6      T
37  5934357.519 -14.1      T
38  5934357.519 -14.6      T

[732 rows x 3 columns]

In [26]:
unique_values = big_new_df['Facies'].unique()
print(unique_values)

[5 2 7 1 3 6 8 4 9 0]

In [22]:
facies_mapping = {'T':0, 'U':1, 'fS':2, 'mS':3, 'gS':4, 'S':5, 'G':6, 'H':7, 'Fkm':8, 'Mg':9}
df['Facies'] = df['Facies'].replace(facies_mapping)

In [23]:
df.rename({'Y': 'X', 'Z':'Y'}, axis=1, inplace=True)
df

              X     Y  Facies
0   5934259.557   5.1       5
1   5934259.557   4.7       2
2   5934259.557   4.2       5
3   5934259.557   3.7       5
4   5934259.557   3.2       5
..          ...   ...     ...
34  5934357.519 -12.6       0
35  5934357.519 -13.1       0
36  5934357.519 -13.6       0
37  5934357.519 -14.1       0
38  5934357.519 -14.6       0

[732 rows x 3 columns]

In [24]:
folder_path = "C:\\Users\\Gerrit\\Desktop\\Masterarbeit\\masterarbeit_gerrit-main\\data_processed"  # Pfad zum Ordner
file_name = "Querschnitt565756E_perfekt.csv"
file_path = os.path.join(folder_path, file_name)

In [25]:
with open(file_path, mode='w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(df.columns)
    for row in df.itertuples(index=False):
        writer.writerow(row)
    print("Die Tabelle wurde als CSV-Datei gespeichert.")

Die Tabelle wurde als CSV-Datei gespeichert.